Models/Chat.cs
namespace Espadon.Models
{
    public class Chat
    {
        public Chat()
        {
            Messages = new List<Message>();
            Users = new List<ChatUser>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public ChatType Type { get; set; }
        public ICollection<Message> Messages { get; set; }
        public ICollection<ChatUser> Users { get; set; }
    }
}

Models/ChatType.cs
namespace Espadon.Models
{
    public enum ChatType
    {
        Room,
        Private
    }
}

Models/ChatUser.cs
namespace Espadon.Models
{
    public class ChatUser
    {
        public string UserId { get; set; }
        public User User { get; set; }
        public int ChatId { get; set; }
        public Chat Chat { get; set; }
        public UserRole Role { get; set; }
    }
}

Models/Message.cs
namespace Espadon.Models
{
    public class Message
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public DateTime Timestamp { get; set; }

        public int ChatId { get; set; }
        public Chat Chat { get; set; }
    }
}

Models/User.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;

namespace Espadon.Models
{
    public class User : IdentityUser
    {
        public User() : base()
        {
            Chats = new List<ChatUser>();
        }
        public ICollection<ChatUser> Chats { get; set; }
    }
}

Models/UserRole.cs
namespace Espadon.Models
{
    public enum UserRole
    {
        Admin,
        Member,
        Guest
    }
}

Controllers/AccountController.cs
using System.Threading.Tasks;
using Espadon.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Espadon.Controllers
{
    public class AccountController : Controller
    {
        private UserManager<User> _userManager;
        private SignInManager<User> _signInManager;

        public AccountController(
            UserManager<User> userManager,
            SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Register() => View();

        [HttpPost]
        public async Task<IActionResult> Register(string username, string password)
        {
            var user = new User
            {
                UserName = username
            };

            var result = await _userManager.CreateAsync(user, password);

            if (result.Succeeded)
            {
                await _signInManager.SignInAsync(user, false);

                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Register", "Account");
        }

        [HttpGet]
        public IActionResult Login() => View();

        [HttpPost]
        public async Task<IActionResult> Login(string username, string password)
        {
            var user = await _userManager.FindByNameAsync(username);

            if (user != null)
            {
                var result = await _signInManager.PasswordSignInAsync(user, password, false, false);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            return RedirectToAction("Login", "Account");
        }

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Login", "Account");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Espadon.Database;
using Espadon.Hubs;
using Espadon.Infrastructure;
using Espadon.Infrastructure.Respository;
using Espadon.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;

namespace Espadon.Controllers
{
    [Authorize]
    public class HomeController : BaseController
    {
        private IChatRepository _repo;
        public HomeController(IChatRepository repo) => _repo = repo;
        public IActionResult Index()
        {
            var chats = _repo.GetChats(GetUserId());

            return View(chats);
        }

        public IActionResult Find([FromServices] AppDbContext ctx)
        {
            var users = ctx.Users
                .Where(x => x.Id != User.GetUserId())
                .ToList();

            return View(users);
        }

        public IActionResult Private()
        {
            var chats = _repo.GetPrivateChats(GetUserId());

            return View(chats);
        }

        public async Task<IActionResult> CreatePrivateRoom(string userId)
        {
            var id = await _repo.CreatePrivateRoom(GetUserId(), userId);

            return RedirectToAction("Chat", new { id });
        }

        [HttpGet("{id}")]
        public IActionResult Chat(int id)
        {
            return View(_repo.GetChat(id));
        }

        [HttpPost]
        public async Task<IActionResult> CreateRoom(string name)
        {
            await _repo.CreateRoom(name, GetUserId());
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> JoinRoom(int id)
        {
            await _repo.JoinRoom(id, GetUserId());

            return RedirectToAction("Chat", "Home", new { id = id });
        }

        public async Task<IActionResult> SendMessage(
            int roomId,
            string message,
            [FromServices] IHubContext<ChatHub> chat)
        {
            var Message = await _repo.CreateMessage(roomId, message, User.Identity.Name);

            await chat.Clients.Group(roomId.ToString())
                .SendAsync("RecieveMessage", new
                {
                    Text = Message.Text,
                    Name = Message.Name,
                    Timestamp = Message.Timestamp.ToString("dd/MM/yyyy hh:mm:ss")
                });

            return Ok();
        }
    }
}

VievComponents/RoomViewComponent.cs
using System.Linq;
using System.Security.Claims;
using Espadon.Database;
using Espadon.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Espadon.VievComponents
{
    public class RoomViewComponent : ViewComponent
    {
        private AppDbContext _context;

        public RoomViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke()
        {
            var userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var chats = _context.ChatUsers
                .Include(x => x.Chat)
                .Where(x => x.UserId == userId
                    && x.Chat.Type == ChatType.Room)
                .Select(x => x.Chat)
                .ToList();

            return View(chats);
        }
    }
}

Views/Home/Chat.cshtml
@model Chat

<div class="chat-body">
    @foreach(var message in Model.Messages){
    <div class="message">
        <header>@message.Name:</header>
        <p>@message.Text</p>
        <footer>@message.Timestamp</footer>
    </div>
    }
</div>
<form class="chat-input" onsubmit="sendMessage(event)" asp-controller="Home" asp-action="CreateMessage">
    <input type="hidden" name="roomId" value="@Model.Id">
    <input type="text" name="message" id="message-input">
    <button type="submit">Send</button>
</form>

@section scripts {
<script src="~/js/signalr.min.js"></script>
<script src="~/js/messageBuilder.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
    var connection = new signalR.HubConnectionBuilder()
        .withUrl("/chatHub")
        .build();
    var _connectionId = '';
    connection.on("RecieveMessage", function (data) {
        var message = messageBuilder()
            .createMessage()
            .withHeader(data.name)
            .withParagraph(data.text)
            .withFooter(data.timestamp)
            .build();
        document.querySelector('.chat-body').append(message);
    })
    connection.start()
        .then(function () {
            connection.invoke('joinRoom', '@Model.Id');
        })
        .catch(function (err) {
            console.log(err)
        })
    window.addEventListener('onunload', function () {
        connection.invoke('leaveRoom', '@Model.Id');
    })
    var sendMessage = function (event) {
        event.preventDefault();
        var data = new FormData(event.target);
        document.getElementById('message-input').value = '';
        axios.post('/Home/SendMessage', data)
            .then(res => {
                console.log("Message Sent!")
            })
            .catch(err => {
                console.log("Failed to send message!")
            })
    }
</script>
}

Views/Home/Find.cshtml
@model IEnumerable<User>

    @foreach(var user in Model){
    <div>
        <a asp-controller="Home" asp-action="CreatePrivateRoom" asp-route-userId="@user.Id">
            @user.UserName
        </a>
    </div>
    }

Views/Home/Index.cshtml
@model IEnumerable<Chat>

    <div class="chat-body">
        @foreach(var chat in Model) {
        <a class="room-button" asp-controller="Home" asp-action="JoinRoom" asp-route-id="@chat.Id">
            @chat.Name
        </a>
        }
    </div>

Views/Shared/Components/Room/Default.cshtml
@model IEnumerable<Chat>

    <div class="side-menu">
        @foreach(var chat in Model){
        <a class="room-button" asp-controller="Home" asp-action="Chat" asp-route-id="@chat.Id">
            @chat.Name
        </a>
        }

        <a class="room-button" id="create-room-btn" href="#">
            <strong>+</strong>
        </a>
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Espadon</title>

    <link rel="stylesheet" href="~/css/site.css">

</head>

<body>

    <div class="navbar">
        <a asp-controller="Home" asp-action="Index">Home</a>
        <a asp-controller="Home" asp-action="Find">Find</a>
        <a asp-controller="Home" asp-action="Private">Private</a>
    </div>

    <div class="main">
        @if(User.Identity.IsAuthenticated){
        <vc:room></vc:room>
        }
        <div class="chat">
            @RenderBody()
        </div>
    </div>

    <div class="modal" id="create-room-modal">
        <form asp-controller="Home" asp-action="CreateRoom" class="modal-body">
            <button type="button" class="close" onclick="closeModal()">X</button>
            <header>Create Room</header>
            <div>
                <input name="name">
            </div>
            <footer>
                <button>Create</button>
            </footer>
        </form>
    </div>

    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", false)

</body>

</html>